
[build]
  command = "vite build"
  publish = "build"

[[headers]]
  for = "/*.js"
    [headers.values]
      Content-Type = "application/javascript"

[[headers]]
  for = "/*.jsx"
    [headers.values]
      Content-Type = "application/javascript"


[[redirects]]
from = "/*"
to = "/index.html"
status = 200